name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version'
        required: true

jobs:
  release:
    environment: deploy
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Compiler
        run: |
          curl -L ${{ secrets.DELPHI_COMPILER_URL }} -o dcc32.zip
          unzip dcc32.zip

      - name: Compile
        run: |
          cd dcc32
          .\dcc32.exe -W- -H- ..\FADeepProbe.dpr

      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: v${{ github.event.inputs.version }}
          draft: true
          prerelease: true

      - name: Upload Exe
        id: upload-exe
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: FADeepProbe.exe
          asset_name: FADeepProbe.exe
          asset_content_type: application/vnd.microsoft.portable-executable
